"""nis2-brinkman-rice-gaia -- LKM-derived NiS2 Brinkman-Rice subgraph.

Generated by lkm-to-gaia from the chain-backed root claim
gcn_29401e4284574aa2.
"""

from .paper_friedemann2016 import *
from .cross_paper import *
from .priors import PRIORS


__all__ = [
    "gcn_29401e42_nis2_brinkman_rice",
]
