"""kondo-brinkman-rice-gaia -- LKM-derived Gaia extension subgraph.

Generated by lkm-to-gaia from the selected chain-backed root claim
gcn_7ae79f122f1c4fcb.
"""

from .paper_anderson1984 import *
from .cross_paper import *

__all__ = [
    "gcn_7ae79f_kondo_brinkman_rice_fixed_point",
]
