"""cemo-kadowaki-wilson-gaia -- LKM-derived Gaia extension subgraph.

Generated by lkm-to-gaia from the selected chain-backed root claim
gcn_bc46d7d5f5284a0e.
"""

from .paper_paramanik2013 import *
from .cross_paper import *

__all__ = [
    "gcn_bc46d7_cemo_kw_wilson_fl_consistency",
]
