"""mott-entropy-mass-gaia -- Gaia package generated from LKM evidence.

Generated by lkm-to-gaia for the Brinkman-Rice entropy/effective-mass root.
Root claim: gcn_e4ecd721edd14d3f.
"""

from .paper_capone2001 import *
from .cross_paper import *
from .priors import PRIORS


__all__ = [
    "gcn_e4ecd721edd14d3f",
]
