"""lurh2si2-small-fs-reference-gaia -- LKM-derived Gaia subgraph.

Generated by lkm-to-gaia.
Search query: narrow target root evidence JSON for LuRh2Si2 small-Fermi-surface reference.
Root claims: gcn_2b8dd97abcb44d53
"""

from .paper_friedemann2013 import *
from .cross_paper import *

__all__ = [
    "gcn_2b8dd97_lurh2si2_reference_reanalysis",
]
