"""ybrh2si2-effective-mass-gaia -- LKM-derived Gaia package.

Generated by lkm-to-gaia from the chain-backed root claim
gcn_2741cdef209a457a.
"""

from .paper_shaginyan2010 import *
from .cross_paper import *

__all__ = [
    "gcn_2741cdef_practical_effective_mass_scheme",
]
