"""ybrh2si2-rbc-hall-gaia -- LKM-derived Gaia extension subgraph.

Generated by lkm-to-gaia from the selected chain-backed root claim
gcn_42a4ff7fd004413f.
"""

from .paper_friedemann2010 import *
from .cross_paper import *

__all__ = [
    "gcn_42a4ff_rbc_hall_dos_values",
]
