"""he3-effective-mass-gaia -- Gaia package generated from LKM evidence.

Generated by lkm-to-gaia for the two-root pilot.
Root claim: gcn_800070efac5e476d.
"""

from .paper_alvesalo1979 import *
from .cross_paper import *
from .priors import PRIORS


__all__ = [
    "gcn_800070efac5e476d",
]
